Add proxy support article
Minestom/minestom.net pull request #14
Opened 2024-07-03 11:27 UTC by zax71

2024-07-23 04:35 UTC, zax71 commented
I didn’t mention Bungee here, I presume it is supported but I’ve never done it myself. If someone could chime in on that then that would be helpful

2024-07-24 13:07 UTC, mworzala requested changes

2024-07-24 13:07 UTC, mworzala commented on docs/feature/proxy-support.md
> +You need to install [Guva](https://github.com/google/guava) to transfer players. Once doing that, just add the below to send the appropriate packet
You do not need guava to create this buffer. You can use the `NetworkBuffer` api:

Also should link to https://docs.papermc.io/paper/dev/plugin-messaging#what-did-we-just-do somewhere.

```
        p.sendPluginMessage("BungeeCord", NetworkBuffer.makeArray(buffer -> {
            buffer.write(NetworkBuffer.STRING, "Connect");
            buffer.write(NetworkBuffer.STRING, "lobby");
        }));
```

2024-07-24 13:07 UTC, mworzala commented
> I didn’t mention Bungee here, I presume it is supported but I’ve never done it myself. If someone could chime in on that then that would be helpful

Bungee is supported via `BungeeCordProxy.enable()`, and BungeeGuard is supported by adding `BungeeCordProxy.setBungeeGuardTokens(Set.of("tokens", "here"))`

2024-07-24 13:19 UTC, zax71 commented
Thanks for the feedback! I’m on holiday currently so it’ll probably be a week or two before I can address these.

2024-07-24 13:25 UTC, mworzala commented
No problem, have a nice holiday

2024-09-19 02:11 UTC, mworzala approved these changes

2024-09-19 02:11 UTC, merged